In [6]:
!python detect.py --weights 16-55-new.pt --conf 0.5 --source capture04.jpeg --device cpu 

Namespace(weights=['16-55-new.pt'], source='capture04.jpeg', img_size=640, conf_thres=0.5, iou_thres=0.45, device='cpu', view_img=False, save_txt=False, save_conf=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', exist_ok=False, no_trace=False)
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
IDetect.fuse
 Convert model to Traced-model... 
 traced_script_module saved! 
 model is traced! 

tensor([545.00000, 218.00000, 788.00000, 580.00000,   0.96534,   1.00000])
545 218 788 580 666.5 399.0 0
tensor([627.00000, 243.00000, 659.00000, 309.00000,   0.88376,   6.00000])
545 218 788 580 643.0 276.0 0
tensor([717.00000, 315.00000, 732.00000, 341.00000,   0.86759,   5.00000])
545 218 788 580 724.5 328.0 0
tensor([235.00000, 147.00000, 340.00000, 328.00000,   0.86277,   1.00000])
545 218 788 580 287.5 237.5 0
235 147 340 328 287.5 237.5 1
tensor([560.00000, 480.00000, 580.00000, 5

YOLOR  2023-10-25 torch 2.1.0+cu118 CPU

c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 314 layers, 36519530 parameters, 6194944 gradients, 103.3 GFLOPS
c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:348: InconsistentVersionWarning: Trying to unpickle estimator SimpleImputer from version 1.2.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\ACER\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:348: InconsistentVersio

In [29]:
import cv2
import pytesseract
from PIL import Image

Image.open('H3141NB.jpg')
# print(pytesseract.image_to_string(Image.open('test.jpeg')))
print(pytesseract.image_to_string(Image.open('H3141NB.jpg')))


TesseractNotFoundError: tesseract is not installed or it's not in your PATH. See README file for more information.

In [ ]:
import joblib
import pandas as pd
NBsave = "C:\TA\yolov7\pipeline_filenameTrain2.pkl"
loaded_pipeline = joblib.load(NBsave)
readNB = pd.read_csv("C:\TA\yolov7\\runs\detect\exp259\capture03.csv")
predictions = loaded_pipeline.predict(readNB)
print (predictions)